.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IPEX" "1" "August 2013" "" ""
.
.SH "NAME"
\fBipex\fR \- IP/Mac Address Extractor
.
.SH "SYNOPSIS"
\fBipex FILE [\-m THRESHOLD] [\-i THRESHOLD] [\-d OUTPUT_DIR]\fR
.
.SH "DESCRIPTION"
Find and extract IP and MAC addresses in FILE\. Addresses with repeat occurrences greater than or equal to a given threshold are logged to ip_addrs\.txt and mac_addrs\.txt respectively\. By default, MAC addresses that occur at least 8 times are logged and IP addresses that occur at least 10 times are logged\. All matches are performed as case insensitive\.
.
.SH "OPTIONS"
.
.TP
\fB\-m\fR
Set the MAC address threshold, defaults to 8
.
.TP
\fB\-i\fR
Set the IP address threshold, defaults to 10
.
.TP
\fB\-d\fR
Specify directory where MAC and IP output files are written to, defaults to current directory
.
.SH "FORMATS"
Matches the following address formats:
.
.IP "\(bu" 4
IPv4: standard format a\.b\.c\.d
.
.IP "\(bu" 4
IPv6: canonical format a:b:c:d:e:f:g:h
.
.IP "\(bu" 4
IPv6: compressed format a::b
.
.IP "\(bu" 4
IPv6: IPv4 mapped IPv6 format a:b:c:d:e:f:w\.x\.y\.z
.
.IP "\(bu" 4
IPv6: compressed IPv4 mapped IPv6 format a::b:w\.x\.y\.z
.
.IP "\(bu" 4
MAC: Separated by \'\-\' aa\-bb\-cc\-dd\-ee\-ff
.
.IP "\(bu" 4
MAC: Separated by \':\' aa:bb:cc:dd:ee:ff
.
.IP "" 0
.
.SH "NOTE ON LARGE FILES"
Depending on how large the file is, this utility can take a long time to complete: for a 512MB file with (5 million) entries it took just over 2 min \-\- YMMV depending on your hardware
